### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by 921942877** [Colin3191/campus_event_bulletin_server#1]
老哥 我这儿没数据 该怎么办啊 我邮箱是2954965330@qq.com 求教!!!

**Comment by Colin3191** [comment]
> 
> 
> 老哥 我这儿没数据 该怎么办啊 我邮箱是[2954965330@qq.com](mailto:2954965330@qq.com) 求教!!!

**Comment by Colin3191** [comment]
> 
> 
> 老哥 我这儿没数据 该怎么办啊 我邮箱是[2954965330@qq.com](mailto:2954965330@qq.com) 求教!!!
